
// Static array of each virtual key's macro name, its ID, and its description on MSDN
#include "framework.h"

#include "VirtualKeys.h"

VKeyStruct VKeys::get_vkeystruct_from_vkeyid(int VKeyID)
{
    ASSERT(VKeyID >= 1 && VKeyID <= 254);
    return VKeyList[VKeyID - 1];
}

VKeyStruct VKeys::get_vkeystruct(int index)
{
    ASSERT(index >= 0 && index <= 253);
    return VKeyList[index];
}

VKeyStruct VKeys::VKeyList[254] = // (exclude 0x00 and 0xFF)
{
    { _T("VK_LBUTTON"),             0x01,       _T("LMB") },
    { _T("VK_RBUTTON"),             0x02,       _T("RMB") },
    { _T("VK_CANCEL"),              0x03,       _T("Control-break processing") },
    { _T("VK_MBUTTON"),             0x04,       _T("MMB") },
    { _T("VK_XBUTTON1"),            0x05,       _T("MB4") },
    { _T("VK_XBUTTON2"),            0x06,       _T("MB5") },
    { _T("-"),                      0x07,       _T("Undefined") },
    { _T("VK_BACK"),                0x08,       _T("BACKSPACE") },
    { _T("VK_TAB"),                 0x09,       _T("TAB") },
    { _T("-"),                      0x0A,       _T("Reserved") },
    { _T("-"),                      0x0B,       _T("Reserved") },
    { _T("VK_CLEAR"),               0x0C,       _T("CLEAR") },
    { _T("VK_RETURN"),              0x0D,       _T("ENTER") },
    { _T("-"),                      0x0E,       _T("Undefined") },
    { _T("-"),                      0x0F,       _T("Undefined") },

    { _T("VK_SHIFT"),               0x10,       _T("SHIFT") },
    { _T("VK_CONTROL"),             0x11,       _T("CTRL") },
    { _T("VK_MENU"),                0x12,       _T("ALT") },
    { _T("VK_PAUSE"),               0x13,       _T("PAUSE") },
    { _T("VK_CAPITAL"),             0x14,       _T("CAPS LOCK") },
    //{ _T("VK_KANA"),                0x15,       _T("IME Kana mode") },
    //{ _T("VK_HANGUEL"),             0x15,       _T("IME Hanguel mode") },
    { _T("VK_HANGUL"),              0x15,       _T("IME Hangul mode") },
    { _T("-"),                      0x16,       _T("Undefined") },
    { _T("VK_JUNJA"),               0x17,       _T("IME Junja mode") },
    { _T("VK_FINAL"),               0x18,       _T("IME final mode") },
    //{ _T("VK_HANJA"),               0x19,       _T("IME Hanja mode") },
    { _T("VK_KANJI"),               0x19,       _T("IME Kanji mode") },
    { _T("-"),                      0x1A,       _T("Undefined") },
    { _T("VK_ESCAPE"),              0x1B,       _T("ESC") },
    { _T("VK_CONVERT"),             0x1C,       _T("IME convert") },
    { _T("VK_NONCONVERT"),          0x1D,       _T("IME nonconvert") },
    { _T("VK_ACCEPT"),              0x1E,       _T("IME accept") },
    { _T("VK_MODECHANGE"),          0x1F,       _T("IME mode change request") },
    
    { _T("VK_SPACE"),               0x20,       _T("SPACEBAR") },
    { _T("VK_PRIOR"),               0x21,       _T("PAGE UP") },
    { _T("VK_NEXT"),                0x22,       _T("PAGE DOWN") },
    { _T("VK_END"),                 0x23,       _T("END") },
    { _T("VK_HOME"),                0x24,       _T("HOME") },
    { _T("VK_LEFT"),                0x25,       _T("LEFT ARROW") },
    { _T("VK_UP"),                  0x26,       _T("UP ARROW") },
    { _T("VK_RIGHT"),               0x27,       _T("RIGHT ARROW") },
    { _T("VK_DOWN"),                0x28,       _T("DOWN ARROW") },
    { _T("VK_SELECT"),              0x29,       _T("SELECT") },
    { _T("VK_PRINT"),               0x2A,       _T("PRINT") },
    { _T("VK_EXECUTE"),             0x2B,       _T("EXECUTE") },
    { _T("VK_SNAPSHOT"),            0x2C,       _T("PRINT SCREEN") },
    { _T("VK_INSERT"),              0x2D,       _T("INS") },
    { _T("VK_DELETE"),              0x2E,       _T("DEL") },
    { _T("VK_HELP"),                0x2F,       _T("HELP") },

    { _T("0 key"),                  0x30,       _T("0") },
    { _T("1 key"),                  0x31,       _T("1") },
    { _T("2 key"),                  0x32,       _T("2") },
    { _T("3 key"),                  0x33,       _T("3") },
    { _T("4 key"),                  0x34,       _T("4") },
    { _T("5 key"),                  0x35,       _T("5") },
    { _T("6 key"),                  0x36,       _T("6") },
    { _T("7 key"),                  0x37,       _T("7") },
    { _T("8 key"),                  0x38,       _T("8") },
    { _T("9 key"),                  0x39,       _T("9") },
    { _T("undefined"),              0x3A,       _T("undefined") },
    { _T("undefined"),              0x3B,       _T("undefined") },
    { _T("undefined"),              0x3C,       _T("undefined") },
    { _T("undefined"),              0x3D,       _T("undefined") },
    { _T("undefined"),              0x3E,       _T("undefined") },
    { _T("undefined"),              0x3F,       _T("undefined") },

    { _T("undefined"),              0x40,       _T("undefined") },
    { _T("A key"),                  0x41,       _T("A") },
    { _T("B key"),                  0x42,       _T("B") },
    { _T("C key"),                  0x43,       _T("C") },
    { _T("D key"),                  0x44,       _T("D") },
    { _T("E key"),                  0x45,       _T("E") },
    { _T("F key"),                  0x46,       _T("F") },
    { _T("G key"),                  0x47,       _T("G") },
    { _T("H key"),                  0x48,       _T("H") },
    { _T("I key"),                  0x49,       _T("I") },
    { _T("J key"),                  0x4A,       _T("J") },
    { _T("K key"),                  0x4B,       _T("K") },
    { _T("L key"),                  0x4C,       _T("L") },
    { _T("M key"),                  0x4D,       _T("M") },
    { _T("N key"),                  0x4E,       _T("N") },
    { _T("O key"),                  0x4F,       _T("O") },

    { _T("P key"),                  0x50,       _T("P") },
    { _T("Q key"),                  0x51,       _T("Q") },
    { _T("R key"),                  0x52,       _T("R") },
    { _T("S key"),                  0x53,       _T("S") },
    { _T("T key"),                  0x54,       _T("T") },
    { _T("U key"),                  0x55,       _T("U") },
    { _T("V key"),                  0x56,       _T("V") },
    { _T("W key"),                  0x57,       _T("W") },
    { _T("X key"),                  0x58,       _T("X") },
    { _T("Y key"),                  0x59,       _T("Y") },
    { _T("Z key"),                  0x5A,       _T("Z") },
    { _T("VK_LWIN"),                0x5B,       _T("Left Windows") },
    { _T("VK_RWIN"),                0x5C,       _T("Right Windows") },
    { _T("VK_APPS"),                0x5D,       _T("Applications") },
    { _T("-"),                      0x5E,       _T("Reserved") },
    { _T("VK_SLEEP"),               0x5F,       _T("Computer Sleep") },

    { _T("VK_NUMPAD0"),             0x60,       _T("Numpad 0") },
    { _T("VK_NUMPAD1"),             0x61,       _T("Numpad 1") },
    { _T("VK_NUMPAD2"),             0x62,       _T("Numpad 2") },
    { _T("VK_NUMPAD3"),             0x63,       _T("Numpad 3") },
    { _T("VK_NUMPAD4"),             0x64,       _T("Numpad 4") },
    { _T("VK_NUMPAD5"),             0x65,       _T("Numpad 5") },
    { _T("VK_NUMPAD6"),             0x66,       _T("Numpad 6") },
    { _T("VK_NUMPAD7"),             0x67,       _T("Numpad 7") },
    { _T("VK_NUMPAD8"),             0x68,       _T("Numpad 8") },
    { _T("VK_NUMPAD9"),             0x69,       _T("Numpad 9") },
    { _T("VK_MULTIPLY"),            0x6A,       _T("Multiply") },
    { _T("VK_ADD"),                 0x6B,       _T("Add") },
    { _T("VK_SEPARATOR"),           0x6C,       _T("Separator") },
    { _T("VK_SUBTRACT"),            0x6D,       _T("Subtract") },
    { _T("VK_DECIMAL"),             0x6E,       _T("Decimal") },
    { _T("VK_DIVIDE"),              0x6F,       _T("Divide") },

    { _T("VK_F1"),                  0x70,       _T("F1") },
    { _T("VK_F2"),                  0x71,       _T("F2") },
    { _T("VK_F3"),                  0x72,       _T("F3") },
    { _T("VK_F4"),                  0x73,       _T("F4") },
    { _T("VK_F5"),                  0x74,       _T("F5") },
    { _T("VK_F6"),                  0x75,       _T("F6") },
    { _T("VK_F7"),                  0x76,       _T("F7") },
    { _T("VK_F8"),                  0x77,       _T("F8") },
    { _T("VK_F9"),                  0x78,       _T("F9") },
    { _T("VK_F10"),                 0x79,       _T("F10") },
    { _T("VK_F11"),                 0x7A,       _T("F11") },
    { _T("VK_F12"),                 0x7B,       _T("F12") },
    { _T("VK_F13"),                 0x7C,       _T("F13") },
    { _T("VK_F14"),                 0x7D,       _T("F14") },
    { _T("VK_F15"),                 0x7E,       _T("F15") },
    { _T("VK_F16"),                 0x7F,       _T("F16") },

    { _T("VK_F17"),                 0x80,       _T("F17") },
    { _T("VK_F18"),                 0x81,       _T("F18") },
    { _T("VK_F19"),                 0x82,       _T("F19") },
    { _T("VK_F20"),                 0x83,       _T("F20") },
    { _T("VK_F21"),                 0x84,       _T("F21") },
    { _T("VK_F22"),                 0x85,       _T("F22") },
    { _T("VK_F23"),                 0x86,       _T("F23") },
    { _T("VK_F24"),                 0x87,       _T("F24") },
    { _T("-"),                      0x88,       _T("Unassigned") },
    { _T("-"),                      0x89,       _T("Unassigned") },
    { _T("-"),                      0x8A,       _T("Unassigned") },
    { _T("-"),                      0x8B,       _T("Unassigned") },
    { _T("-"),                      0x8C,       _T("Unassigned") },
    { _T("-"),                      0x8D,       _T("Unassigned") },
    { _T("-"),                      0x8E,       _T("Unassigned") },
    { _T("-"),                      0x8F,       _T("Unassigned") },

    { _T("VK_NUMLOCK"),             0x90,       _T("NUM LOCK") },
    { _T("VK_SCROLL"),              0x91,       _T("SCROLL LOCK") },
    { _T("-"),                      0x92,       _T("OEM specific") },
    { _T("-"),                      0x93,       _T("OEM specific") },
    { _T("-"),                      0x94,       _T("OEM specific") },
    { _T("-"),                      0x95,       _T("OEM specific") },
    { _T("-"),                      0x96,       _T("OEM specific") },
    { _T("-"),                      0x97,       _T("Unassigned") },
    { _T("-"),                      0x98,       _T("Unassigned") },
    { _T("-"),                      0x99,       _T("Unassigned") },
    { _T("-"),                      0x9A,       _T("Unassigned") },
    { _T("-"),                      0x9B,       _T("Unassigned") },
    { _T("-"),                      0x9C,       _T("Unassigned") },
    { _T("-"),                      0x9D,       _T("Unassigned") },
    { _T("-"),                      0x9E,       _T("Unassigned") },
    { _T("-"),                      0x9F,       _T("Unassigned") },

    { _T("VK_LSHIFT"),              0xA0,       _T("Left SHIFT") },
    { _T("VK_RSHIFT"),              0xA1,       _T("Right SHIFT") },
    { _T("VK_LCONTROL"),            0xA2,       _T("Left CONTROL") },
    { _T("VK_RCONTROL"),            0xA3,       _T("Right CONTROL") },
    { _T("VK_LMENU"),               0xA4,       _T("Left MENU") },
    { _T("VK_RMENU"),               0xA5,       _T("Right MENU") },
    { _T("VK_BROWSER_BACK"),        0xA6,       _T("Browser Back") },
    { _T("VK_BROWSER_FORWARD"),     0xA7,       _T("Browser Forward") },
    { _T("VK_BROWSER_REFRESH"),     0xA8,       _T("Browser Refresh") },
    { _T("VK_BROWSER_STOP"),        0xA9,       _T("Browser Stop") },
    { _T("VK_BROWSER_SEARCH"),      0xAA,       _T("Browser Search") },
    { _T("VK_BROWSER_FAVORITES"),   0xAB,       _T("Browser Favorites") },
    { _T("VK_BROWSER_HOME"),        0xAC,       _T("Browser Start and Home") },
    { _T("VK_VOLUME_MUTE"),         0xAD,       _T("Volume Mute") },
    { _T("VK_VOLUME_DOWN"),         0xAE,       _T("Volume Down") },
    { _T("VK_VOLUME_UP"),           0xAF,       _T("Volume Up") },

    { _T("VK_MEDIA_NEXT_TRACK"),    0xB0,       _T("Next Track") },
    { _T("VK_MEDIA_PREV_TRACK"),    0xB1,       _T("Previous Track") },
    { _T("VK_MEDIA_STOP"),          0xB2,       _T("Stop Media") },
    { _T("VK_MEDIA_PLAY_PAUSE"),    0xB3,       _T("Play/Pause Media") },
    { _T("VK_LAUNCH_MAIL"),         0xB4,       _T("Start Mail") },
    { _T("VK_LAUNCH_MEDIA_SELECT"), 0xB5,       _T("Select Media") },
    { _T("VK_LAUNCH_APP1"),         0xB6,       _T("Start Application 1") },
    { _T("VK_LAUNCH_APP2"),         0xB7,       _T("Start Application 2") },
    { _T("-"),                      0xB8,       _T("Reserved") },
    { _T("-"),                      0xB9,       _T("Reserved") },
    { _T("VK_OEM_1"),               0xBA,       _T("';:' keyS") },
    { _T("VK_OEM_PLUS"),            0xBB,       _T("'+'") },
    { _T("VK_OEM_COMMA"),           0xBC,       _T("','") },
    { _T("VK_OEM_MINUS"),           0xBD,       _T("'-'") },
    { _T("VK_OEM_PERIOD"),          0xBE,       _T("'.'") },
    { _T("VK_OEM_2"),               0xBF,       _T("'/?'") },

    { _T("VK_OEM_3"),               0xC0,       _T("'`~'") },
    { _T("-"),                      0xC1,       _T("Reserved") },
    { _T("-"),                      0xC2,       _T("Reserved") },
    { _T("-"),                      0xC3,       _T("Reserved") },
    { _T("-"),                      0xC4,       _T("Reserved") },
    { _T("-"),                      0xC5,       _T("Reserved") },
    { _T("-"),                      0xC6,       _T("Reserved") },
    { _T("-"),                      0xC7,       _T("Reserved") },
    { _T("-"),                      0xC8,       _T("Reserved") },
    { _T("-"),                      0xC9,       _T("Reserved") },
    { _T("-"),                      0xCA,       _T("Reserved") },
    { _T("-"),                      0xCB,       _T("Reserved") },
    { _T("-"),                      0xCC,       _T("Reserved") },
    { _T("-"),                      0xCD,       _T("Reserved") },
    { _T("-"),                      0xCE,       _T("Reserved") },
    { _T("-"),                      0xCF,       _T("Reserved") },

    { _T("-"),                      0xD0,       _T("Reserved") },
    { _T("-"),                      0xD1,       _T("Reserved") },
    { _T("-"),                      0xD2,       _T("Reserved") },
    { _T("-"),                      0xD3,       _T("Reserved") },
    { _T("-"),                      0xD4,       _T("Reserved") },
    { _T("-"),                      0xD5,       _T("Reserved") },
    { _T("-"),                      0xD6,       _T("Reserved") },
    { _T("-"),                      0xD7,       _T("Reserved") },
    { _T("-"),                      0xD8,       _T("Unassigned") },
    { _T("-"),                      0xD9,       _T("Unassigned") },
    { _T("-"),                      0xDA,       _T("Unassigned") },
    { _T("VK_OEM_4"),               0xDB,       _T("'[{'") },
    { _T("VK_OEM_5"),               0xDC,       _T("'\\|'") },
    { _T("VK_OEM_6"),               0xDD,       _T("']}'") },
    { _T("VK_OEM_7"),               0xDE,       _T("'/\")") },
    { _T("VK_OEM_8"),               0xDF,       _T("Undefined") },

    { _T("-"),                      0xE0,       _T("Reserved") },
    { _T("-"),                      0xE1,       _T("OEM specific") },
    { _T("VK_OEM_102"),             0xE2,       _T("</>") },
    { _T("-"),                      0xE3,       _T("OEM specific") },
    { _T("-"),                      0xE4,       _T("OEM specific") },
    { _T("VK_PROCESSKEY"),          0xE5,       _T("IME PROCESS") },
    { _T("-"),                      0xE6,       _T("OEM specific") },
    { _T("VK_PACKET"),              0xE7,       _T("Undefined") },
    { _T("-"),                      0xE8,       _T("Unassigned") },
    { _T("-"),                      0xE9,       _T("OEM specific") },
    { _T("-"),                      0xEA,       _T("OEM specific") },
    { _T("-"),                      0xEB,       _T("OEM specific") },
    { _T("-"),                      0xEC,       _T("OEM specific") },
    { _T("-"),                      0xED,       _T("OEM specific") },
    { _T("-"),                      0xEE,       _T("OEM specific") },
    { _T("-"),                      0xEF,       _T("OEM specific") },

    { _T("-"),                      0xF0,       _T("OEM specific") },
    { _T("-"),                      0xF1,       _T("OEM specific") },
    { _T("-"),                      0xF2,       _T("OEM specific") },
    { _T("-"),                      0xF3,       _T("OEM specific") },
    { _T("-"),                      0xF4,       _T("OEM specific") },
    { _T("-"),                      0xF5,       _T("OEM specific") },
    { _T("VK_ATTN"),                0xF6,       _T("Attn") },
    { _T("VK_CRSEL"),               0xF7,       _T("CrSel") },
    { _T("VK_EXSEL"),               0xF8,       _T("ExSel") },
    { _T("VK_EREOF"),               0xF9,       _T("Erase EOF") },
    { _T("VK_PLAY"),                0xFA,       _T("Play") },
    { _T("VK_ZOOM"),                0xFB,       _T("Zoom") },
    { _T("VK_NONAME"),              0xFC,       _T("Reserved") },
    { _T("VK_PA1"),                 0xFD,       _T("PA1") },
    { _T("VK_OEM_CLEAR"),           0xFE,       _T("Clear key") }
};